### ISSUE TITLE
JS code dictionaries

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/django-zxcvbn-password#2]
ZXCVBN js code should import dictionaries from files instead of hardcoding them. It would allow us to use dictionaries from other languages too (currently only english).  
It would also be great to be able to choose which dicts are used when using the app.

**Comment by Pawamoy** [comment]
No relevant anymore with new zxcvbn-python code. Developers can add checks of their own (other dicts).

**Comment by pawamoy** [comment]
This was implemented server-side in #95. If you need custom dictionaries on the client side, please open a new issue.
