### ISSUE TITLE
Django 1.8 LTS

### ISSUE THREAD

**Issue by pacanukeha** [pawamoy/django-zxcvbn-password#24]
So 1.8 is on LTS support until at least April 2018. Is there any chance that we can get a 2.0.x release that supports 1.8?

**Comment by Pawamoy** [comment]
I'm open to pull requests if you want to re-add support for Django 1.8. The thing is that Django 1.9 introduced the password validators setting, and I don't really see how to make it fit into 1.8 :/

**Comment by pawamoy** [comment]
Closing as 1.8 LTS is now done!
