### ISSUE TITLE
Color indicator

### ISSUE THREAD

**Issue by Pawamoy** [Pawamoy/django-zxcvbn-password#3]
The strength meter should go green only if it has reached the required entropy.
The color is currently based on fixed values.

**Comment by shacker** [comment]
Agreed. The `min_score` attribute in the validator settings dict is only enforced on submit, and does not interact with the JS scoring. So it's possible to have the bar go green and then be told on submit that your password is too weak (depending on the score you set). Not an ideal user experience.

We somehow need to get the min_score value from django settings into the JS. I would do this by defining a super simple hidden view that returns the min_score from settings as json, then load that json at the top of password_strength.js (and then match against it).

**Comment by Pawamoy** [comment]
Good idea! Feel free to send a PR ;) Otherwise I'll do this when I have some time.

**Comment by Pawamoy** [comment]
This was fixed without using async call from the client :stuck_out_tongue: 

We simply add the min score value in the markup when rendering the password widget. JavaScript then uses this value to set the strength bar color accordingly.
