### ISSUE TITLE
Confusing help_text

### ISSUE THREAD

**Issue by mimi89999** [Pawamoy/django-zxcvbn-password#46]
The _Your password must be stronger._ suggestion added as a rule under the _New password_ field is very confusing for users. I think you misunderstood what `get_help_text` is for.

![capture du 2018-03-07 19-19-54](https://user-images.githubusercontent.com/8530546/37110205-8c609f44-223c-11e8-8f56-2bb140ddd6db.png)

> get_help_text(): provide a help text to explain the requirements to the user.

**Comment by Pawamoy** [comment]
Hi, thanks for your feedback :wave: !

What would you suggest to improve the help text?

**Comment by Pawamoy** [comment]
Oh yes I see what you mean now, thanks to the screenshot :confused:.

Would something like `The ZXCVBN score of your password must be higher than X"?

**Comment by mimi89999** [comment]
I have no clue. I think both messages are too confusing for simple users. They have no clue what is ZXCVBN or password entropy.

**Comment by Pawamoy** [comment]
What about `strength` instead of `entropy`? Or maybe we can simply get rid of the `get_help_text` method. I can't find this method in Django's own validators...

**Comment by mimi89999** [comment]
It seems to be required: https://github.com/django/django/blob/master/django/contrib/auth/password_validation.py

**Comment by Pawamoy** [comment]
Yep, just saw that. I can still return an empty string.

**Comment by mimi89999** [comment]
I think that _Your password can't contain repeated words or characters._ would be good.

**Comment by mimi89999** [comment]
I tried returning an empty string, but an empty `<li>` gets added in the HTML code.

**Comment by Pawamoy** [comment]
`Your password can't contain repeated words or characters` sounds good to me. Should we go with that?

**Comment by iwaron** [comment]
Yep, that sounds more exact than previous message

**Comment by mRokita** [comment]
I think that should be an error message, not a help text.

**Comment by Pawamoy** [comment]
Yes you are correct, previously I used an error message for both. Now we clearly have a help text and a validation error message (which can maybe also be improved ;))
