### ISSUE TITLE
Release 2.0.1 to pypi?

### ISSUE THREAD

**Issue by slinkymanbyday** [pawamoy/django-zxcvbn-password#58]
Hi,
It seems the v2.0.0 does not work with Django 2.1 (TypeError on render), however the latest github version does. Just wondering if there are any plans to release 2.0.1 to pypi anytime soon?

thanks.

**Comment by pawamoy** [comment]
Hello! Sorry for the delay, I just came back from vacations. I'm gonna update the CHANGELOG today and then release the new version :slightly_smiling_face:

**Comment by pawamoy** [comment]
Just released 2.0.2 :+1:
