### ISSUE TITLE
Bootstrap 4 classes

### ISSUE THREAD

**Issue by YPCrumble** [pawamoy/django-zxcvbn-password#59]
Bootstrap 4 has [new classes for the progress bar background color](https://getbootstrap.com/docs/4.1/components/progress/#backgrounds).

I'd be happy to help with a PR for any of these fixes:

- Updating this repo to support Bootstrap 4 and documenting that Bootstrap 3 users need to add the new Bootstrap 4 classes
- Adding a `BOOTSTRAP_VERSION` variable that defaults to version 4 but allows the user to set it to version 3 if they're using the old version of bootstrap
- Leaving it the way it is now and just documenting that Bootstrap 4 users need to add the old Bootstrap 3 classes as I've done

Thanks for building this!

**Comment by pawamoy** [comment]
Hello! Sorry for the delay, I just came back from vacations.

I think the second point is the best. The app would take care of using the right classes depending on a setting variable (`BOOTSTRAP_VERSION`? or `ZXCVBN_PASSWORD_BOOTSTRAP_VERSION`?), and the user would just have to update this variable, not the classes themselves.

**Comment by pawamoy** [comment]
Will likely not work on this project anymore.
