### ISSUE TITLE
Allow a customizable warning message with variables

### ISSUE THREAD

**Issue by YPCrumble** [pawamoy/django-zxcvbn-password#60]
What I'm looking for is rather than the text showing "Warning: This password would take {{ password_strength_time }} to crack", something like "Password Strength: {{ zxcvbn_score }}".

I'd use Django's `render_to_string` so that I could use template tags. This would allow me to do something like:

    PASSWORD_STRENGTH_WARNING = "Password strength: {% if zxcvbn_score < 2 %}Weak{% else %}Strong{% endif %}"

Default implementation would be the current message so this would only apply to users who want to override the warning message.

Is this something you'd entertain? Thanks again for building and maintaining this library!

**Comment by pawamoy** [comment]
Hello! Sorry for the delay, I just came back from vacations.

I think I would like that indeed, because I was never quite satisfied with the current messages. If you want to give it a try and send a PR, it will be welcomed :slightly_smiling_face:

**Comment by pawamoy** [comment]
Will likely not work on this project anymore.
