### ISSUE TITLE
Use updated zxcvbn python library.

### ISSUE THREAD

**Issue by dwolfhub** [Pawamoy/django-zxcvbn-password#7]
I've worked to create an updated zxcvbn python library based on the newest JS codebase and to also support python3. My port is now listed as the suggested python port on the main zxcvbn repository readme. Since Django will soon not support python2 you may want to consider changing your dependency to my library. Let me know if I can help in any way.

https://github.com/dwolfhub/zxcvbn-python

**Comment by Pawamoy** [comment]
Oh this is great! I will take a look to see what is needed to integrate your library into this app :) Thanks for you work :+1:

**Comment by Pawamoy** [comment]
I think I'll use the new feature in Django 1.9 (https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#module-django.contrib.auth.password_validation) to add a ZXCVBN password validator.

The PasswordField for forms will validate password client-side with zxcvbn's javascript (need to update it). The developer will be able to extend the password validation server-side with other user inputs with a call from the form clean method: validate_password(password, User(field1=value1, ...)). The fields given to user should correspond to the validator's fields specified in settings. 

By default, the server-side validation will check the password without any other user inputs (can't pass/predict them).

**Comment by dwolfhub** [comment]
Sounds good to me.

**Comment by NickStefan** [comment]
@Pawamoy 
custom validator, using `python-zxcvbn` could look like this:

```
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
from zxcvbn import zxcvbn

class ZxcvbnValidator(object):
    def __init__(self, min_score=2):
        self.min_score = min_score

    def validate(self, password, user=None):
        results = zxcvbn(password)
        if results.get('score', 0) < self.min_score:
            feedback = ', '.join(results.get('feedback', {}).get('suggestions', []))
            raise ValidationError(
                _(feedback),
                code='password_too_weak',
                params={},
            )

    def get_help_text(self):
        return _(
            "Your password must be stronger."
        )

```

 and then in the settings.py something like:
```
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django-zxcvbn-password.ZxcvbnValidator'
    },
]
```

**Comment by dwolfhub** [comment]
I have generally used 3 as a minimum.

```
0 # too guessable: risky password. (guesses < 10^3)
1 # very guessable: protection from throttled online attacks. (guesses < 10^6)
2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)
3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)
4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)
```

**Comment by NickStefan** [comment]
when you put it that way, 3 does sound like a better default

**Comment by Pawamoy** [comment]
Okay I've pushed some commits to implement this. Django 1.8 is not supported anymore. Let me know if something is wrong so I can fix it before releasing on PyPI.
