### ISSUE TITLE
Using deprecated dependency

### ISSUE THREAD

**Issue by rollcat** [pawamoy/django-zxcvbn-password#74]
Latest release on PyPi is still using [zxcvbn-python](https://pypi.org/project/zxcvbn-python/), which is deprecated, as it changed name to [zxcvbn](https://pypi.org/project/zxcvbn/). This raises a deprecation warning.

**Comment by pawamoy** [comment]
Hi, thank you for the heads up :slightly_smiling_face: I'm gonna open a PR right now.

**Comment by pawamoy** [comment]
Will release tomorrow.

**Comment by pawamoy** [comment]
Released 2.0.3.

**Comment by rollcat** [comment]
Thank you, just upgraded my projects ;)
